terminate called after throwing an instance of 'std::out_of_range'
  what():  stoi
Aborted (core dumped)

WNiosek: Każda zmienna ma ograniczoną ilość pamięci, przez co po przekroczeniu jej granicy wyskakuje błąd i program nie jest w stanie tego obsłużyć.
